name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install packages
        run: npm i -g expo eas
             yarn install
             npm run build:android
